<!-- Form for updating product details in step 3 -->
 <style>
    div#custom-text p { font-size: 11px; color: #808080ab !important; }
 </style>
<form id="form_step_3" action="{{ route('products.updateStep3', $product) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="row mt-3">
        <div class="col-lg-10 col-md-10 col-sm-12 col-12">
            <div class="row mb-4">
                <div class="col-md-6 col-sm-6 col-12">
                    <!-- <div class="units_weights_title mb-3">Units and Weights</div> -->
                    <label class="form-label">Ingredients <span class="material-symbols-outlined ms-3" id="refreshIcon" style="cursor: pointer;">refresh</span></label>
                    <div class="quill-editor-wrapper">
                        <div id="ingredientsEditor" class="quill-editor text-dark-mud" data-input="labelling_ingredients_override"></div>
                        <!-- <input type="hidden" name="labelling_ingredients_override" value="{{ old('labelling_ingredients_override', $product->labelling_ingredients_override ?: $product->labelling_ingredients) }}"> -->
                        <input type="hidden" name="labelling_ingredients_override" value="{{$product->labelling_ingredients}}">
                        @error('labelling_ingredients_override')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-12">
                    <label class="form-label"></label>
                    <div class="form-group mt-md-5 pt-3">
                        @php
                            $remove = ['Soya', 'Soybean'];
                            $cleaned = preg_replace('/\s*,\s*/', ', ', trim(preg_replace('/,+/', ',', str_replace($remove, '', $product->labelling_allergens)), ', '));

                            $formattedIngredients = [];
                            $ingredientsStr = $product->labelling_ingredients;

                            // Step 1: Preserve commas by splitting with regex (captures words and commas separately)
                            preg_match_all('/[^,\s]+|,/', $ingredientsStr, $matches);
                            $ingredientsArray = $matches[0];

                            // Convert allergens to lowercase and trim spaces
                            $allergen = array_map('strtolower', array_map('trim', $allergen));

                            // Step 2: Process each ingredient while preserving commas
                            foreach ($ingredientsArray as $ing) {
                                $cleanIng = strtolower(trim($ing, '()')); // Remove parentheses for checking

                                if ($ing === ',') {
                                    $formattedIngredients[] = ','; // Keep commas as they are
                                } elseif (in_array($cleanIng, $allergen)) {
                                    $formattedIngredients[] = '<strong>' . $ing . '</strong>';
                                } else {
                                    $formattedIngredients[] = $ing;
                                }
                            }

                            $formattedIngredients = implode(' ', $formattedIngredients);
                            $formattedIngredients = str_replace(" ,",",", $formattedIngredients);
                        @endphp
                        <div id="ingredient-auto" class="autogenerated_lebel font-body">{!! $formattedIngredients !!}</div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-6 col-sm-6 col-12">
                    <label class="form-label">Allergens <span class="material-symbols-outlined ms-3" id="allergensrefresh" style="cursor: pointer;">refresh</span></label>
                    <div class="quill-editor-wrapper">
                        <div id="allergens-editor" class="quill-editor text-dark-mud" data-input="labelling_allergens_override"></div>
                        <!-- <input type="hidden" name="labelling_allergens_override" value="{{ old('labelling_allergens_override', $product->labelling_allergens_override ?: $cleaned) }}"> -->
                        <input type="hidden" name="labelling_allergens_override" value="{{$cleaned}}">
                        @error('labelling_allergens_override')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-12">
                    <label class="form-label"></label>
                    <div class="form-group mt-md-5 pt-3">
                        <b>
                            <div id="allergens-auto" class="autogenerated_lebel font-body">{{ $cleaned }}</div>
                        </b>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-6 col-sm-6 col-12">
                    <label class="form-label">May Be Present <span class="material-symbols-outlined ms-3" id="refresh-maybe" style="cursor: pointer;">refresh</span></label>
                    <div class="quill-editor-wrapper">
                        <div id="may-be-editor" class="quill-editor text-dark-mud" data-input="labelling_may_contain_override"></div>
                        <input type="hidden" name="labelling_may_contain_override" value="{{ old('labelling_may_contain_override', $product->labelling_may_contain_override ?: ($profile->commonAllergens ?? '')) }}">
                        @error('labelling_may_contain_override')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-12">
                    <label class="form-label"></label>
                    <div class="form-group mt-md-5 pt-3">
                        <b>
                            <div id="may-be-auto" class="autogenerated_lebel font-body">{{ old('labelling_may_contain', $product->labelling_may_contain ?: ($profile->commonAllergens ?? '')) }}</div>
                        </b>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col-md-6 col-sm-6 col-12">
                    <div class="input-group input-group-dynamic flex-column mb-4">
                        <label class="form-label">Manufacturing Location</label>
                        <select name="company_factory" id="company_factory" class="form-control-select js-example-basic-single">
                            <option disabled {{ old('company_factory', optional($product)->company_factory) ? '' : 'selected' }}>Select Manufacturing Location</option>
                            @if($companyProfile['factory'])
                            @foreach($companyProfile['factory'] as $factory)
                                <option value="{{ $factory->id }}"
                                    {{ old('company_factory', optional($product)->bproduct_status) == $factory->id ? 'selected' : '' }}>
                                    {{ $factory->location_name }}
                                </option>
                            @endforeach
                            @endif
                        </select>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-12">
                    <div class="input-group input-group-dynamic flex-column mb-4">
                        <label class="form-label">Compliance Officer</label>
                        <select name="company_keyperson" id="company_keyperson" class="form-control-select js-example-basic-single">
                            <option disabled {{ old('company_keyperson', optional($product)->company_keyperson) ? '' : 'selected' }}>Select Compliance Officer</option>
                            @if($companyProfile['keyperson'])
                            @foreach($companyProfile['keyperson'] as $keyperson)
                                @php 
                                $checkDetails = json_decode($keyperson->key_personnel);
                                @endphp
                                @if(isset($checkDetails->is_compliance_officer))
                                <option value="{{ $keyperson->id }}"
                                    {{ old('company_keyperson', optional($product)->bproduct_status) == $keyperson->id ? 'selected' : '' }}>
                                    {{ $keyperson->keyperson_name }}
                                </option>
                                @endif
                            @endforeach
                            @endif
                        </select>
                    </div>
                </div>
            </div>




            
            <input type="hidden" id="check_prod_label" value="@if($prod_labels) 1 @else 0 @endif">
            <div class="row mb-4">
                <label class="form-label">Sutiability to make certain claims</label>
                <p class="primary-text-dark">Specify if the product is suitable for use in product intended for the following consumer uses.</p>
                <table class="table responsiveness mx-3" id="dynamicIngredients">
                    <thead>
                        <tr>
                            <th class="primary-text-dark fw-bold" width="40%"></th>
                            <th class="primary-text-dark fw-bold" width="13%">Specify if suitable for (Y/N)</th>
                            <th class="primary-text-dark fw-bold" width="30%">How has this been validated?</th>
                            <th class="primary-text-dark fw-bold" width="17%">Certificate available (Y/N)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(['Halal','Kosher','Organic','Biodynamic','Octo-lacto-vegetarian','Lacto-vegetarian','Vegan'] as $index => $suits)
                        @php
                            $pr_label = "";
                            switch ($suits) {
                                case 'Biodynamic':
                                    $pr_label = "bio";
                                    break;
                                case 'Octo-lacto-vegetarian':
                                    $pr_label = "octo";
                                    break;
                                case 'Lacto-vegetarian':
                                    $pr_label ="lacto"; 
                                    break;
                                default:
                                    $pr_label = strtolower($suits);
                                    break;
                            }
                        @endphp
                        <tr>
                            <td class="primary-text-dark">{{$suits}}</td>
                            <td>
                                @php $rm = "rm_{$pr_label}_yn"; @endphp
                                <select class="suit_section form-select suitable_select" name="rm_{{$pr_label}}_yn">
                                    <option value="Yes" @if($prod_labels && $prod_labels->$rm == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->$rm == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->$rm == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                            <td>
                                @php $rm1 = "rm_{$pr_label}_validated"; @endphp
                                <select class="suit_section form-select" name="rm_{{$pr_label}}_validated">
                                    <option value="Based on ingredients" @if($prod_labels && $prod_labels->$rm1 == "Based on ingredients") selected @endif >Based on ingredients</option>
                                    <option value="Through certification" @if($prod_labels && $prod_labels->$rm1 == "Through certification") selected @endif>Through certification</option>
                                    <option value="na" @if($prod_labels && $prod_labels->$rm1 == "na") selected @endif>na</option>
                                </select>
                            </td>
                            <td>
                                @php $rm2 = "rm_{$pr_label}_certification_yn"; @endphp
                                <select class="suit_section form-select" name="rm_{{$pr_label}}_certification_yn">
                                    <option value="Yes" @if($prod_labels && $prod_labels->$rm2 == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->$rm2 == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->$rm2 == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                <label class="form-label mt-4">Durability, Packaging and Supply Chain</label>
                <table class="table responsiveness mx-3" id="dynamicIngredients1">
                    <thead>
                        <tr>
                            <th class="text-primary-orange" width="40%"></th>
                            <th class="text-primary-orange" width="13%"></th>
                            <th class="text-primary-orange" width="30%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="height: 50px;">
                            <td class="primary-text-dark fw-bold">As supplied (unopened pack or bulk)</td><td></td><td></td>
                        </tr>
                        <tr>
                            <td class="primary-text-dark">Shelf Life:</td>
                            <td>
                            <input type="text" name="rm_supplied_shelf_life_num" class="form-control text-right numeric-input"  placeholder="Type shelf life and storage as you want it to appear on label" value="@if($prod_labels){{$prod_labels->rm_supplied_shelf_life_num}}@endif" />
                            </td>
                            <td>
                                <select class="suit_section form-select" name="rm_supplied_shelf_life_units">
                                    <option value="Days" @if($prod_labels && $prod_labels->rm_supplied_shelf_life_units == "Days") selected @endif>Days</option>
                                    <option value="Weeks" @if($prod_labels && $prod_labels->rm_supplied_shelf_life_units == "Weeks") selected @endif>Weeks</option>
                                    <option value="Months" @if($prod_labels && $prod_labels->rm_supplied_shelf_life_units == "Months") selected @endif>Months</option>
                                    <option value="Years" @if($prod_labels && $prod_labels->rm_supplied_shelf_life_units == "Years") selected @endif>Years</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="primary-text-dark">Temperature controlled during storage:</td>
                            <td>
                                <select class="suit_section form-select" name="rm_suppied_temp_control_storage_num">
                                    <option value="Yes" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_num == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_num == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_num == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                            <td>
                                <select class="suit_section form-select" name="rm_suppied_temp_control_storage_degrees">
                                    <option value="≤ 20°C (Ambient)" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_degrees == "≤ 20°C (Ambient)") selected @endif>≤ 20°C (Ambient)</option>
                                    <option value="≤ 5°C (Refridgerated)" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_degrees == "≤ 5°C (Refridgerated)") selected @endif>≤ 5°C (Refridgerated)</option>
                                    <option value="≤ -15 (Frozen)" @if($prod_labels && $prod_labels->rm_suppied_temp_control_storage_degrees == "≤ -15 (Frozen)") selected @endif>≤ -15 (Frozen)</option>
                                </select>
                            </td>
                        </tr>

                        <tr>
                            <td class="primary-text-dark">Temperature controlled during transport:</td>
                            <td>
                                <select class="suit_section form-select" name="rm_supplied_temp_control_transport_yn">
                                    <option value="Yes" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_yn == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_yn == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_yn == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                            <td>
                                <select class="suit_section form-select" name="rm_supplied_temp_control_transport_degrees">
                                    <option value="≤ 20°C (Ambient)" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_degrees == "≤ 20°C (Ambient)") selected @endif>≤ 20°C (Ambient)</option>
                                    <option value="≤ 5°C (Refridgerated)" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_degrees == "≤ 5°C (Refridgerated)") selected @endif>≤ 5°C (Refridgerated)</option>
                                    <option value="≤ -15 (Frozen)" @if($prod_labels && $prod_labels->rm_supplied_temp_control_transport_degrees == "≤ -15 (Frozen)") selected @endif>≤ -15 (Frozen)</option>
                                </select>
                            </td>
                        </tr>

                        <tr style="height: 50px;">
                            <td class="primary-text-dark fw-bold">Product - Once in Use (resealable pack or bulk container)</td><td></td><td></td>
                        </tr>

                        <tr>
                            <td class="primary-text-dark">Shelf Life:</td>
                            <td>
                            <input type="text" name="rm_inuse_shelf_life_num" class="form-control text-right numeric-input" value="@if($prod_labels){{$prod_labels->rm_inuse_shelf_life_num}}@endif" />
                            </td>
                            <td>
                                <select class="suit_section form-select" name="rm_inuse_shelf_life_units">
                                    <option value="Days" @if($prod_labels && $prod_labels->rm_inuse_shelf_life_units == "Days") selected @endif>Days</option>
                                    <option value="Weeks" @if($prod_labels && $prod_labels->rm_inuse_shelf_life_units == "Weeks") selected @endif>Weeks</option>
                                    <option value="Months" @if($prod_labels && $prod_labels->rm_inuse_shelf_life_units == "Months") selected @endif>Months</option>
                                    <option value="Years" @if($prod_labels && $prod_labels->rm_inuse_shelf_life_units == "Years") selected @endif>Years</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="primary-text-dark">Temperature controlled during storage:</td>
                            <td>
                                <select class="suit_section form-select" name="rm_inuse_temp_control_storage_num">
                                    <option value="Yes" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_num == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_num == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_num == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                            <td>
                                <select class="suit_section form-select" name="rm_inuse_temp_control_storage_degrees">
                                    <option value="≤ 20°C (Ambient)" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_degrees == "≤ 20°C (Ambient)") selected @endif>≤ 20°C (Ambient)</option>
                                    <option value="≤ 5°C (Refridgerated)" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_degrees == "≤ 5°C (Refridgerated)") selected @endif>≤ 5°C (Refridgerated)</option>
                                    <option value="≤ -15 (Frozen)" @if($prod_labels && $prod_labels->rm_inuse_temp_control_storage_degrees == "≤ -15 (Frozen)") selected @endif>≤ -15 (Frozen)</option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                <table class="table responsiveness mx-3 mt-4" id="dynamicIngredients2">
                    <thead style="display:none;">
                        <tr>
                            <th class="text-primary-orange" width="50%"></th>
                            <th class="text-primary-orange" width="50%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="height: 50px;">
                            <td class="primary-text-dark fw-bold">Other</td><td></td>
                        </tr>

                        <tr>
                            <td class="primary-text-dark">Specifiy any other storage requirements::</td>
                            <td>
                            <select class="suit_section form-select" name="rm_storage_requirement">
                                    <option value="Once opened, store in an airtight container in a cool, dry place (≤ 20°C)." @if($prod_labels && $prod_labels->rm_storage_requirement == "Once opened, store in an airtight container in a cool, dry place (≤ 20°C).") selected @endif>Once opened, store in an airtight container in a cool, dry place (≤ 20°C).</option>
                                    <option value="Once opened, store in an airtight container and keep refrigerated (≤ 5°C)." @if($prod_labels && $prod_labels->rm_storage_requirement == "Once opened, store in an airtight container and keep refrigerated (≤ 5°C).") selected @endif>Once opened, store in an airtight container and keep refrigerated (≤ 5°C).</option>
                                    <option value="Once opened, store in an airtight container and keep frozen (≤ -15°C)." @if($prod_labels && $prod_labels->rm_storage_requirement == "Once opened, store in an airtight container and keep frozen (≤ -15°C).") selected @endif>Once opened, store in an airtight container and keep frozen (≤ -15°C).</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="primary-text-dark">Indended use:</td>
                            <td>
                                <select class="suit_section form-select" name="rm_indended_use">
                                    <option value="This product is intended for general consumption"  @if($prod_labels && $prod_labels->rm_indended_use == "This product is intended for general consumption") selected @endif>This product is intended for general consumption</option>
                                    <option value="For general consumption"  @if($prod_labels && $prod_labels->rm_indended_use == "For general consumption") selected @endif>For general consumption</option>
                                    <option value="Other"  @if($prod_labels && $prod_labels->rm_indended_use == "Other") selected @endif>Other</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="primary-text-dark">Specifiy type of date mark to be used:</td>
                            <td>
                                <select class="suit_section form-select" name="rm_date_mark">
                                    <option value="Use Before" @if($prod_labels && $prod_labels->rm_date_mark == "Use Before") selected @endif>Use Before</option>
                                    <option value="Best Before" @if($prod_labels && $prod_labels->rm_date_mark == "Best Before") selected @endif>Best Before</option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <label class="form-label mt-4">Hazards</label>
                <table class="table responsiveness mx-3" id="dynamicIngredients3">
                    <thead>
                        <tr>
                            <th class="text-primary-orange" width="80%"></th>
                            <th class="text-primary-orange" width="20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="primary-text-dark">Are there any potential hazards associated with the product?</td>
                            <td>
                                <select class="suit_section form-select" name="rm_hazard_yn">
                                    <option value="Yes" @if($prod_labels && $prod_labels->rm_hazard_yn == "Yes") selected @endif>Yes</option>
                                    <option value="No" @if($prod_labels && $prod_labels->rm_hazard_yn == "No") selected @endif>No</option>
                                    <option value="Unknown" @if($prod_labels && $prod_labels->rm_hazard_yn == "Unknown") selected @endif>Unknown</option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <div id="custom-text">
                    <p>Potentially hazardous food means food that has to be kept at certain temperatures to minimise the growth of any pathogenic microorganisms that may be present in the food or to prevent the formation of toxins in the food. (Source: STANDARD 3.2.2 FOOD SAFETY PRACTICES AND GENERAL REQUIREMENTS </p>
                </div>

            </div>
            <div class="row mb-4">
                @php 
                    $prodIngs = $prod_ings;
                @endphp
                @if($prodIngs->isNotEmpty())
                <x-product-allergens :prodIngs="$prodIngs" />
                @endif
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 col-12">
            <div class="button-row grid-btn">
                <a href="{{ route('products.edit', ['product' => $product->id, 'step' => 2]) }}"
                    class="btn btn-secondary-blue mb-0 me-1 js-btn-previous" title="Previous">Back</a>
                <button class="btn btn-secondary-blue mb-0 me-1 js-btn-save" type="button" title="Save">Save</button>
                <button class="btn btn-secondary-blue mb-0 js-btn-next" type="button" title="Next">Next</button>
            </div>
            <div class="mt-4">
                <x-product-gridcard :product="$product" />
                <x-recipe-details :product="$product" />
                <x-tags-card :product="$product" />
                <x-product-weight :product="$product" />
            </div>
        </div>
    </div>
</form>