<script>
    // Javascript for product form step 3
    $(document).ready(function() {

        get_product_allergens();
        $('#refreshIcon').click(function() {
            var autogeneratedLabel = $('#ingredient-auto').html();
            $('#ingredientsEditor .ql-editor').html('');
            $('#ingredientsEditor .ql-editor').html('<p>' + autogeneratedLabel + '</p>');
        });

        $('#allergensrefresh').click(function() {
            var autogeneratedLabel = $('#allergens-auto').text();
            $('#allergens-editor .ql-editor').html('');
            $('#allergens-editor .ql-editor').html(autogeneratedLabel);
        });

        $('#refresh-maybe').click(function() {
            var autogeneratedLabel = $('#may-be-auto').text();
            $('#may-be-editor .ql-editor').html('');
            $('#may-be-editor .ql-editor').html(autogeneratedLabel);
        });


        var allergens = @json($allergen);
        
        // Function to apply bold to allergens inside the editor
        function boldAllergensInEditor() {
            var editorText = $('#ingredientsEditor .ql-editor').html();
            $.each(allergens, function(i, allergen) {
                var regex = new RegExp("\\b" + allergen + "\\b", "gi");  // Create a case-insensitive regex for the allergen word
                editorText = editorText.replace(regex, '<b>' + allergen + '</b>');  // Wrap allergens in <b> tags
            });
            $('#ingredientsEditor .ql-editor').html(editorText);

            var htmlContent = $('#ingredientsEditor .ql-editor').html();
            $('input[name="labelling_ingredients_override"]').val(htmlContent);
        }

        boldAllergensInEditor();


        let product = "{{$product->id}}"
        let isFormChanged = false;
        let idleTime = 0;
        let ignorePopState = false;

        if (typeof product !== "undefined" && product !== null && product !== '') {
            let idleInterval = setInterval(timerIncrement, 60000); // 1 minute
            $(this).mousemove(resetTimer);
            $(this).keypress(resetTimer);
            $(this).scroll(resetTimer);
            $(this).click(resetTimer);

            function resetTimer() {
                idleTime = 0;
            }

            function timerIncrement() {
                idleTime++;
                if (idleTime == 15) { // 15 minutes
                    Swal.fire({
                        icon: 'warning',
                        title: 'Warning!',
                        text: 'You’ve been inactive for a while. This session will close in 1 minute unless you take action'
                    });
                }else if(idleTime == 16){
                    inactivity_discard();
                }
            }

            editlock_update(); // edit lock update
        }

        function inactivity_discard(){
            let url = "{{ route('products.inactivity', ':id') }}".replace(':id', product);
            $.ajax({
                url: url,
                method: 'GET',
                success: function(response) {
                    if (response.status) {
                       window.location.href = "{{route('products.index')}}";   
                    }
                },
                error: function(xhr) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error!',
                        text: 'An error occurred'
                    });
                }
            }); 
        }

        function editlock_update(){
            let url = "{{ route('products.edit_lock_update', ':id') }}".replace(':id', product);
            $.ajax({
                url: url,
                method: 'GET',
                success: function(response) {
                },
                error: function(xhr) {
                }
            }); 
        }

        $('#form_step_3').on('change input', 'input, select, textarea', function () {
            isFormChanged = true;
        });

        $('.js-btn-save, .js-btn-next').on('click', function () {
            isFormChanged = false;
        });

        window.addEventListener("beforeunload", function (e) {
            if (isFormChanged) {
                e.preventDefault();
                e.returnValue = ''; // Required for Chrome
            }
        });

        window.history.pushState(null, null, window.location.href);
        window.addEventListener('popstate', function (event) {
            if (ignorePopState) return;
            if (isFormChanged) {
                // Push back state again to stop browser back
                window.history.pushState(null, null, window.location.href);
                Swal.fire({
                    title: 'Are you sure you want to exit?',
                    text: "You have unsaved changes. What would you like to do?",
                    icon: 'warning',
                    showCancelButton: true,
                    showDenyButton: true,
                    confirmButtonText: 'Save and Exit',
                    denyButtonText: 'Discard Changes and Exit',
                    cancelButtonText: 'Continue Editing',
                    reverseButtons: true,
                    allowOutsideClick: false,
                    allowEscapeKey: false,
                    allowEnterKey: false
                }).then((result) => {
                    if (result.isConfirmed) {  
                        ignorePopState = true;
                        $('.js-btn-save').click();
                        setTimeout(() => {
                            window.location.href = "{{route('products.index')}}";    
                        }, 1000);
                    } else if (result.isDenied) {
                        isFormChanged = false;
                        ignorePopState = true;
                        inactivity_discard();
                    } else {
                        // Stay on the page
                    }
                });
            }
        });

    });

    function get_product_allergens(){
        let id = "{{$product->id}}"
        $.ajax({
            url: "{{ route('products.get-allergen-summary', ':id') }}".replace(':id', id),
            method: 'GET',
            success: function(response) {
                
            }
        });
    }

    $(document).on('change','select.suitable_select',function(){
        let selectVal = $(this).val()
        if(selectVal == "No"){
            let selectName = $(this).attr('name')
            let splitArray = selectName.split('_')
            $(`select[name="rm_${splitArray[1]}_validated"]`).val('na')
            $(`select[name="rm_${splitArray[1]}_certification_yn"]`).val('No')        
        }
    })

    $(window).on('load',function(){
        let val = $(`#check_prod_label`).val() 
        if(val == ' 0 '){
            $('table#dynamicIngredients tbody tr').each(function(){
                $(this).find('select.suitable_select').val('No').trigger('change')
            })
        }
    })

</script>